name: Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test-api:
    name: Tests - Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Test for Services
        run: npm test